- name: Prepare directory with extra logs
  file: dest=/var/log/extra state=directory
  become: true

# No need to install dstat package here because it is part of the images
- name: Run dstat for collecting metrics during 2 hours
  command: >
    dstat -tcmndrylpg --nocolor --output /var/log/extra/dstat-csv.log 1 7200 \
    >/dev/null
  async: 7200
  poll: 0
  become: true
  when: step_install_undercloud

- name: Install the undercloud
  shell: |
    {{ working_dir }}/undercloud-install.sh > \
    {{ undercloud_install_log }} 2>&1
  when: step_install_undercloud
