####################################
# FEATURESET047 - UNDERCLOUD UPGRADE
# Based on featureset003
####################################

undercloud_generate_service_certificate: false
ssl_overcloud: false
undercloud_check_idempotency: true
undercloud_check_sanity: true
containerized_overcloud: false
containerized_overcloud_upgrade: false

# Tripleo-upgrade specific parameters
undercloud_upgrade: true

# Deactivate validations as there is no overcloud
test_ping: false
run_tempest: false
