# Summary of the feature set.
# Deploy an non-ha Openstack environment, without SSL, introspect, and
# ready to execute tempest tests.
# Example of usage:
# ./quickstart.sh -t all --retain-inventory -c \
# @config/general_config/featureset021.yml -R tripleo-ci/consistent-master \
# -T all $VIRTHOST

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: true
ssl_overcloud: false
overcloud_templates_path: /usr/share/openstack-tripleo-heat-templates
undercloud_templates_path: /usr/share/openstack-tripleo-heat-templates
step_introspect: true

# This enables container deployements after Pike
containerized_overcloud: >-
  {% if release in ['newton', 'ocata', 'pike'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}
delete_docker_cache: true

containerized_undercloud: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

undercloud_custom_env_files: "{{ working_dir }}/undercloud-parameter-defaults.yaml"
undercloud_cloud_domain: "localdomain"
undercloud_undercloud_hostname: "undercloud.{{ undercloud_cloud_domain }}"
undercloud_resource_registry_args:
  "OS::TripleO::Undercloud::Net::SoftwareConfig": "{{ undercloud_templates_path }}/ci/common/net-config-simple-bridge.yaml"

# Tell tripleo about our environment
enable_pacemaker: false
network_isolation: false

extra_args: ''

# keep the doc gen settings at the bottom of the config file.
# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - "{% if release not in ['newton', 'ocata', 'pike'] -%}overcloud-prep-containers{%- endif -%}"
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
    - tempest-setup
    - "{% if run_tempest|bool and tempest_format|default('packages') == 'containers' -%}tempest_container{%- endif -%}"
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - "{% if release not in ['newton', 'ocata', 'pike'] -%}overcloud-prep-containers{%- endif -%}"
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
    - tempest-setup
    - "{% if run_tempest|bool and tempest_format|default('packages') == 'containers' -%}tempest_container{%- endif -%}"


# Tempest configuration, keep always at the end of the file
# Tempest
# Run containerized tempest from master and ongoing
tempest_format: >-
  {% if release not in ['newton', 'ocata', 'pike', 'queens'] -%}
  container
  {%- else -%}
  packages
  {%- endif -%}
undercloud_enable_tempest: >-
  {% if release not in ['newton', 'ocata', 'pike', 'queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

run_tempest: true
test_regex: '.*'
test_ping: false
# Run tempest without skip file
skip_file_src: ''
# For full tempest run we need to make sure concurrency is not too high
tempest_workers: 3

# Run tempest in containers when at least undercloud is containerized
tempest_format: >-
  {% if containerized_undercloud|bool -%}
  container
  {%- else -%}
  packages
  {%- endif -%}

# Install the latest unlreleased packages from CentOS
enable_centos_cr_repo: true


