##################################################
# FEATURESET050 - CONTAINERIZED UNDERCLOUD UPGRADE
# Based on featureset047
##################################################

undercloud_generate_service_certificate: false
ssl_overcloud: false
undercloud_check_idempotency: true
undercloud_check_sanity: true
containerized_overcloud: false
containerized_overcloud_upgrade: false
containerized_undercloud_upgrade: true

# Tripleo-upgrade specific parameters
undercloud_upgrade: true
tripleo_ci: true
use_oooq: true

# Deactivate validations as there is no overcloud
test_ping: false
run_tempest: false
