# Deploy an Openstack environment with a containerized overcloud
# using scenario004

undercloud_setup: true
network_isolation: false
overcloud_ipv6: false

# pacemaker settings are configured in the scenario template
# do not set `enable_pacemaker` in the featureset

containerized_overcloud: true
undercloud_generate_service_certificate: false

ssl_overcloud: false

step_introspect: false

composable_scenario: scenario004-multinode-containers.yaml
validate_template: scenario004-multinode.yaml
deployed_server: true

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - "{% if run_tempest|bool -%}tempest-setup{%- endif -%}"
    - "{% if run_tempest|bool and tempest_format|default('packages') == 'containers' -%}tempest_container{%- endif -%}"
    - overcloud-validate
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
    - "{% if run_tempest|bool -%}tempest-setup{%- endif -%}"
    - "{% if run_tempest|bool and tempest_format|default('packages') == 'containers' -%}tempest_container{%- endif -%}"
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant

# Use the traditional ping test in newton and ocata
# Run tempest in pike+

test_ping: >-
  {% if release in ['newton', 'ocata'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

run_tempest: >-
  {% if release in ['newton', 'ocata'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

test_white_regex: ''

# Run containerized tempest from master and ongoing
tempest_format: >-
  {% if release not in ['newton', 'ocata', 'pike', 'queens'] -%}
  container
  {%- else -%}
  packages
  {%- endif -%}

tempest_whitelist:
  - 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops'

tempest_extra_config: {'object-storage-feature-enabled.discoverability': 'False', 'service_available.swift': 'False'}

deployed_server: >-
  {% if release in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
deploy_steps_ansible_workflow: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
config_download_args: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  -e /usr/share/openstack-tripleo-heat-templates/environments/config-download-environment.yaml
  -e {{ working_dir }}/config-download.yaml
  --config-download
  --deployed-server
  --disable-validations
  --verbose
  {%- endif -%}
