composable_scenario: multinode-containers.yaml
composable_services: false

network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false
containerized_overcloud: true

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: false

# This enables the deployment of the overcloud with SSL.
ssl_overcloud: false

# This enables the run of several tripleo-validations tests through Mistral
run_tripleo_validations: True
# This enables the run of tripleo-validations negative tests through shell
# scripts
run_tripleo_validations_negative_tests: True
# Exit tripleo-quickstart on validations failure
exit_on_validations_failure: False

# If `run_tempest` is `true`, run tempests tests, otherwise do not
# run them.
test_ping: false
run_tempest: true
test_white_regex: 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops'
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant

deployed_server: >-
  {% if release in ['newton','ocata','pike'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
deploy_steps_ansible_workflow: >-
  {% if release not in ['newton','ocata','pike'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
config_download_args: >-
  {% if release in ['queens'] -%}
  -e /usr/share/openstack-tripleo-heat-templates/environments/config-download-environment.yaml
  --config-download
  --deployed-server
  {%- endif %}
  {% if release not in ['newton','ocata','pike'] -%}
  -e {{ working_dir }}/config-download.yaml
  --disable-validations
  --verbose
  {%- endif -%}
