undercloud_generate_service_certificate: false
enable_opstools_repo: true

# Use the traditional ping test in newton and ocata
# Run tempest in pike+

# pacemaker settings are configured in the scenario template
# do not set `enable_pacemaker` in the featureset

test_ping: >-
  {% if release in ['newton', 'ocata'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

run_tempest: >-
  {% if release in ['newton', 'ocata'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

test_white_regex: ''

# This enables the run of several tripleo-validations tests through Mistral
run_tripleo_validations: True
# This enables the run of tripleo-validations negative tests through shell
# scripts
run_tripleo_validations_negative_tests: True
# Exit tripleo-quickstart on validations failure
exit_on_validations_failure: False

deployed_server: true
composable_scenario: scenario001-multinode.yaml
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant
validate_template: scenario001-multinode.yaml
tempest_whitelist_old:
  - 'tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern'
  - 'ceilometer.tests.tempest.scenario.test_telemetry_integration.TestTelemetryIntegration'
tempest_whitelist_new:
  - 'tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern'
  - 'telemetry_tempest_plugin.scenario.test_telemetry_integration.TestTelemetryIntegration'

tempest_whitelist: >-
  {% if release not in ['newton', 'ocata', 'pike'] -%}{{ tempest_whitelist_new }}
  {%- else -%}{{ tempest_whitelist_old }}
  {%- endif -%}

tempest_plugins_old:
  - python-aodh-tests
  - python-ceilometer-tests
  - python-gnocchi-tests
  - python-panko-tests

tempest_plugins_new:
  - python-telemetry-tests-tempest
  - python-heat-tests-tempest

tempest_plugins: >-
  {% if release not in ['newton', 'ocata', 'pike'] -%}{{ tempest_plugins_new }}
  {%- else -%}{{ tempest_plugins_old }}
  {%- endif -%}
