# Summary of the feature set.
# Deploy an Openstack environment with ssl undercloud, introspect, and use network isolation
# Note, this is the same featureset as 001 but it deploys IPV6

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: true
ssl_overcloud: true
overcloud_templates_path: /usr/share/openstack-tripleo-heat-templates
step_introspect: true
containerized_overcloud: true
delete_docker_cache: true

# Tell tripleo about our environment.
overcloud_ipv6: true
enable_pacemaker: true
network_isolation: true
network_isolation_type: "multiple-nics"
network_isolation_args: >-
  {% if release != 'newton' %}
  -e {{ overcloud_templates_path }}/environments/network-isolation-v6.yaml
  -e {{ overcloud_templates_path }}/ci/environments/network/multiple-nics-ipv6/network-environment.yaml
  -e {{ working_dir }}/network-environment.yaml
  {% else %}
  -e {{ overcloud_templates_path }}/environments/network-isolation-v6.yaml
  -e {{ tripleo_root }}/tripleo-ci/test-environments/ipv6-network-templates/network-environment.yaml
  -e {{ tripleo_root }}/tripleo-ci/test-environments/net-iso.yaml
  -e {{ working_dir }}/network-environment.yaml
  {% endif %}

extra_args: >-
  --ntp-server pool.ntp.org
  -e {{ overcloud_templates_path }}/ci/environments/ovb-ha.yaml

# keep the doc gen settings at the bottom of the config file.
# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate

test_ping: false
run_tempest: true
test_regex: ''
tempest_whitelist:
  - 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops'
