# Deploy an Openstack environment with a containerized overcloud
# using scenario001

undercloud_setup: true
network_isolation: false
overcloud_ipv6: false

# pacemaker settings are configured in the scenario template
# do not set `enable_pacemaker` in the featureset

enable_opstools_repo: true

containerized_overcloud: true
undercloud_generate_service_certificate: false

ssl_overcloud: false

step_introspect: false

composable_scenario: scenario001-multinode-containers.yaml
validate_template: scenario001-multinode.yaml
deployed_server: true

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant

# Use the traditional ping test in newton and ocata
# Run tempest in pike+

test_ping: >-
  {% if release in ['newton', 'ocata'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

run_tempest: >-
  {% if release in ['newton', 'ocata'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

test_regex: ''
tempest_whitelist_old:
  - 'tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern'
  - 'ceilometer.tests.tempest.scenario.test_telemetry_integration.TestTelemetryIntegration'
tempest_whitelist_new:
  - 'tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern'
  - 'telemetry_tempest_plugin.scenario.test_telemetry_integration.TestTelemetryIntegration'
tempest_whitelist: >-
  {% if release not in ['newton', 'ocata', 'pike'] -%}{{ tempest_whitelist_new }}
  {%- else -%}{{ tempest_whitelist_old }}
  {%- endif -%}

tempest_plugins_old:
  - python-aodh-tests
  - python-ceilometer-tests
  - python-gnocchi-tests
  - python-panko-tests
tempest_plugins_new:
  - python-telemetry-tests-tempest
  - python-heat-tests-tempest
tempest_plugins: >-
  {% if release not in ['newton', 'ocata', 'pike'] -%}{{ tempest_plugins_new }}
  {%- else -%}{{ tempest_plugins_old }}
  {%- endif -%}
tempest_extra_config: {'telemetry.alarm_granularity': '60'}

# This is a workaround to have test_volume_boot_pattern passing, it's failing
# due a concurrency, for more information, check lp #1742936
tempest_workers: 1

deployed_server: >-
  {% if release in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
deploy_steps_ansible_workflow: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
config_download_args: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  -e /usr/share/openstack-tripleo-heat-templates/environments/config-download-environment.yaml
  -e {{ working_dir }}/config-download.yaml
  --config-download
  --deployed-server
  --disable-validations
  --verbose
  {%- endif -%}
