# Summary of the feature set.
# Deploy an Openstack environment with OVS configured in the containerized overcloud
composable_scenario: scenario007-multinode-containers.yaml
validate_template: scenario007-multinode.yaml

network_isolation: false
enable_pacemaker: true
overcloud_ipv6: false
containerized_overcloud: true

containerized_undercloud: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

undercloud_templates_path: /usr/share/openstack-tripleo-heat-templates
undercloud_custom_env_files: "{{ working_dir }}/undercloud-parameter-defaults.yaml"
undercloud_cloud_domain: "localdomain"
undercloud_undercloud_hostname: "undercloud.{{ undercloud_cloud_domain }}"

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: false

# This enables the deployment of the overcloud with SSL.
ssl_overcloud: false

# This featureset is extremely resource intensive, so we disable telemetry
# in order to reduce the overall memory footprint
# Disabled by default in ussuri
telemetry_args: >-
   {% if release in ['queens', 'stein', 'train'] %}
   -e {{ overcloud_templates_path }}/environments/disable-telemetry.yaml
   {% endif %}

extra_args: >-
  -e {{ overcloud_templates_path }}/environments/services/neutron-ovs.yaml
  {% if release not in ['train','wallaby'] %}
  -e {{ working_dir }}/ci_custom_firewall_rules.yaml
  {% endif %}
  {% if release not in ['train','ussuri','victoria'] -%}
  --disable-protected-resource-types
  --baremetal-deployment
  {%- endif -%}

composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant

deployed_server: >-
  {% if release in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
deploy_steps_ansible_workflow: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
config_download_args: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  -e {{ working_dir }}/config-download.yaml
  --disable-validations
  --verbose
  {%- endif -%}

ephemeral_heat: "{{ (release not in ['train','ussuri','victoria']) | bool }}"
ephemeral_heat_args: "{{ '--heat-type pod' if ephemeral_heat|bool else '' }}"

# Tempest configuration, keep always at the end of the file

tempest_config: true
test_ping: false
test_white_regex: ''
overcloud_container_cli: >-
  {%- if ansible_distribution in ["RedHat", "CentOS"] and ansible_distribution_major_version|int >= 8 %}podman
  {%- else %}docker{% endif -%}

# os_tempest setting
# Settings for os_tempest

use_os_tempest: >-
  {% if release not in ['pike', 'queens', 'stein'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

# It will create a public network name 'public' using os_tempest
tempest_interface_name: public

# In order to have a public network with external connectivity, we need to use
# flat network type
tempest_public_net_provider_type: flat
tempest_private_net_provider_type: "vlan"
# It is the physical network name through which public network will be created
# having connectivity with external world.
tempest_public_net_physical_name: datacentre

# Setting the tempest_cidr as it is required while creating public subnet from which
# floating IPs gets assigned
tempest_cidr: '192.168.24.0/24'

tempest_private_net_seg_id: ''

tempest_install_method: distro

# Having tempest_network_ping_gateway set to true allows to ping any of the IP from
# router to find out network related issue in the deployment early
tempest_network_ping_gateway: true

# It is the python-tempestconf profile which also consumes tempest-deployer-input file
tempest_tempestconf_profile:
  debug: true
  create: true
  deployer-input: "{{ ansible_user_dir }}/tempest-deployer-input.conf"
  os-cloud: "{{ tempest_cloud_name }}"
  out: "{{ tempest_workspace }}/etc/tempest.conf"
  network-id: "{{ tempest_neutron_public_network_id }}"
  overrides: "{{ tempest_tempest_conf_overrides | default({}) | combine(tempest_tempestconf_profile_overrides | default({}), recursive=True) }}"

tempest_allowed_group: "featureset030"
