# Deploy an Openstack environment with a containerized overcloud
# using scenario001

undercloud_setup: true
network_isolation: false
overcloud_ipv6: false

# pacemaker settings are configured in the scenario template
# do not set `enable_pacemaker` in the featureset

enable_opstools_repo: true

containerized_overcloud: true
undercloud_generate_service_certificate: false

ssl_overcloud: false

step_introspect: false

deploy_composable_scenario: true
composable_scenario: scenario001-multinode-containers.yaml
validate_template: scenario001-multinode.yaml

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant

# Use the traditional ping test in newton and ocata
# Run tempest in pike+

test_ping: >-
  {% if release in ['newton', 'ocata'] -%}
  true
  {%- else -%}
  # TODO(emilien) change it to false when:
  # - https://review.openstack.org/#/c/490376 is merged
  # - https://bugs.launchpad.net/tripleo/+bug/1708793 is fixed
  true
  {%- endif -%}

tempest_config: >-
  {% if release in ['newton', 'ocata'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

run_tempest: >-
  {% if release in ['newton', 'ocata'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

test_regex: ''
tempest_whitelist:
  - 'tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern'
  - 'ceilometer.tests.tempest.scenario.test_telemetry_integration.TestTelemetryIntegration'
tempest_plugins:
  - python-aodh-tests
  - python-ceilometer-tests
  - python-gnocchi-tests
  - python-panko-tests
