composable_scenario: scenario009-multinode.yaml
deployed_server: true

network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false
containerized_overcloud: true

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: false

# This enables the deployment of the overcloud with SSL.
ssl_overcloud: false

# Centos OpenSihft repo
add_repos:
  - type: package
    # NOTE(mandre) centos-release-openshift-origin39 provides the newest
    # packages for 3.9 branch
    pkg_name: centos-release-openshift-origin39

extra_args: ''

container_args: >-
  {% if release in ['pike','queens'] -%}
  -e {{ overcloud_templates_path }}/environments/docker.yaml
  {%- endif -%}
  -e {{ working_dir }}/containers-default-parameters.yaml
  -e {{ overcloud_templates_path }}/environments/openshift.yaml

deploy_steps_ansible_workflow: true
config_download_args: >-
  -e {{ working_dir }}/config-download.yaml
  --disable-validations
  --verbose

composable_roles: true

# NOTE(flaper87): There's likely a better way to do this
repo_cmd_after: |
  sudo yum update -y
  sudo yum install -y openshift-ansible-playbooks

overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant
  - name: Compute
    CountDefault: 0
    tags:
      - compute
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant

# Tempest configuration, keep always at the end of the file
# Run tempest in containers when at least undercloud is containerized
tempest_format: >-
  {% if containerized_undercloud|bool -%}
  container
  {%- else -%}
  packages
  {%- endif -%}

# If `run_tempest` is `true`, run tempests tests, otherwise do not
# run them.
tempest_config: false
test_ping: false
run_tempest: false

