# Summary of the feature set.
# Deploy an Openstack environment with ssl undercloud, introspect, and use network isolation

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: true
ssl_overcloud: true
overcloud_templates_path: /usr/share/openstack-tripleo-heat-templates
step_introspect: true
# force image building
# TODO(gcerami) tripleo-ci specific content. This has to be implemented in another way
to_build: true
# Delete the overcloud after deployment
step_delete_overcloud: true
undercloud_check_idempotency: true

# This enables container deployements after Pike
containerized_overcloud: >-
  {% if release in ['newton', 'ocata', 'pike'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}
delete_docker_cache: true

# Tell tripleo about our environment.
enable_pacemaker: true
network_isolation: true
network_isolation_type: "multiple-nics"
network_isolation_args: >-
  {% if release != 'newton' %}
  -e {{ overcloud_templates_path }}/ci/environments/network/multiple-nics/network-isolation-absolute.yaml
  -e {{ overcloud_templates_path }}/ci/environments/network/multiple-nics/network-environment.yaml
  {%- else -%}
  -e {{ tripleo_root }}/tripleo-ci/test-environments/network-templates/network-isolation-absolute.yaml
  -e {{ tripleo_root }}/tripleo-ci/test-environments/network-templates/network-environment.yaml
  -e {{ tripleo_root }}/tripleo-ci/test-environments/net-iso.yaml
  {%- endif -%}

extra_args: >-
  --ntp-server pool.ntp.org
   {% if release not in ['newton', 'ocata', 'pike'] %}
  -e {{ overcloud_templates_path }}/ci/environments/ovb-ha.yaml
  {% endif %}

# keep the doc gen settings at the bottom of the config file.
# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
    - overcloud-delete
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
    - overcloud-delete

# Use the traditional ping test in newton, ocata and pike
# Run tempest in queens+

test_ping: >-
  {% if release in ['newton', 'ocata', 'pike'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

run_tempest: >-
  {% if release in ['newton', 'ocata', 'pike'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

test_regex: ''
tempest_whitelist:
  - 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops'
