# Summary of the feature set.
# Deploy an Openstack environment with opnfv configured in the overcloud
composable_scenario: scenario008-multinode.yaml
validate_template: scenario008-multinode.yaml
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant

network_isolation: false
enable_pacemaker: true
overcloud_ipv6: false
containerized_overcloud: false

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: false

# This enables the deployment of the overcloud with SSL.
ssl_overcloud: false

# This featureset is extremely resource intensive, so we disable telemetry
# in order to reduce the overall memory footprint
# This is not required in newton
telemetry_args: >-
  {% if release != 'newton' %}
  -e {{ overcloud_templates_path }}/environments/disable-telemetry.yaml
  {% endif %}
  -e {{ overcloud_templates_path }}/environments/neutron-opendaylight.yaml
  --ntp-server pool.ntp.org

extra_args: >-
  -e {{ overcloud_templates_path }}/environments/neutron-opendaylight.yaml
  --ntp-server pool.ntp.org

# If `run_tempest` is `true`, run tempests tests, otherwise do not
# run them.
tempest_config: false
test_ping: true
run_tempest: false

# Add ODL Repo
add_repos:
  - type: generic
    filename: opendaylight.repo
    reponame: opendaylight
    baseurl: http://cbs.centos.org/repos/nfv7-opendaylight-6-testing/\$basearch/os
