composable_scenario: multinode-containers-mixed-os.yaml
composable_services: false

network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false
containerized_overcloud: true

containerized_undercloud: true

undercloud_templates_path: /usr/share/openstack-tripleo-heat-templates
undercloud_custom_env_files: "{{ working_dir }}/undercloud-parameter-defaults.yaml"
undercloud_cloud_domain: "localdomain"
undercloud_undercloud_hostname: "undercloud.{{ undercloud_cloud_domain }}"

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: false

# This enables the deployment of the overcloud with SSL.
ssl_overcloud: false

mixed_os: true

composable_roles: true

overcloud_roles_control:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller

overcloud_roles_compute:
  - name: Compute
    CountDefault: 1
    HostnameFormatDefault: '%stackname%-compute-%index%'
    tags:
      - compute

deployed_server: true
deploy_steps_ansible_workflow: true

config_download_args: >-
  -e {{ working_dir }}/config-download.yaml
  --disable-validations
ephemeral_heat: true
ephemeral_heat_args: "{{ '--heat-type pod' if ephemeral_heat|bool else '' }}"

# Tempest configuration, keep always at the end of the file
test_ping: false
tempest_ping_router: false


# Settings for os_tempest

use_os_tempest: true

tempest_test_whitelist:
  - 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps'
  - 'tempest.api.compute.admin.test_flavors'
  - 'tempest.api.compute.flavors'
  - 'tempest.api.compute.keypairs'
  - 'tempest.api.compute.security_groups'

# https://launchpad.net/bugs/1844446
undercloud_enable_validations: false

undercloud_enable_paunch: false

undercloud_parameter_defaults_args: >-
  {%- if ansible_distribution in ["RedHat", "CentOS"] and ansible_distribution_major_version|int < 8 %}
  {'IronicIPXEUefiSnpOnly': 'false'}
  {%- else -%}
  {'IronicIPXEUefiSnpOnly': 'true'}
  {%- endif -%}
