# Summary of the feature set.
# This is a basic configuration it should match fs001 as
# closely as possible with the exception of the network isolation type

# Deploy an Openstack environment with ssl undercloud, introspect, and use network isolation
# Note: any change in this featureset must also be done in featureset035.

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: true
ssl_overcloud: true
overcloud_templates_path: /usr/share/openstack-tripleo-heat-templates
undercloud_templates_path: /usr/share/openstack-tripleo-heat-templates
step_introspect: true

# This enables container deployements after Pike
containerized_overcloud: >-
  {% if release in ['newton', 'ocata', 'pike'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}
delete_docker_cache: true

containerized_undercloud: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

undercloud_custom_env_files: "{{ working_dir }}/undercloud-parameter-defaults.yaml"
undercloud_cloud_domain: "localdomain"
undercloud_undercloud_hostname: "undercloud.{{ undercloud_cloud_domain }}"

ctlplane_masquerade: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

undercloud_enable_routed_networks: >-
  {% if release not in ['newton','ocata','pike'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

undercloud_clean_nodes: >-
  {% if release not in ['newton','ocata','pike'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

baremetal_provision: >-
  {% if release in ['newton','ocata','pike','queens','stein','train', 'ussuri'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

# Provision composable networks prior to creating the heat stack
network_provision: >-
  {% if release in ['stein','train','ussuri','victoria'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

network_data_yaml: "{{ overcloud_templates_path }}/network-data-samples/default-network-isolation.yaml"
network_isolation_args: >-
  {% if not release in ['train','ussuri','victoria'] -%}
  --networks-file {{ overcloud_templates_path }}/network-data-samples/default-network-isolation.yaml
  -e {{ working_dir }}/overcloud-networks-deployed.yaml
  -e {{ working_dir }}/overcloud-vips-deployed.yaml
  -e {{ overcloud_templates_path }}/environments/net-single-nic-with-vlans.yaml
  -e {{ working_dir }}/network-environment.yaml
  {% endif %}

# Tell tripleo about our environment.
enable_pacemaker: false
network_isolation: true
network_isolation_type: "single-nic-vlans"

# This featureset is extremely resource intensive, so we disable telemetry
# in order to reduce the overall memory footprint
# Disabled by default from ussuri
telemetry_args: >-
   {% if release in ['queens', 'stein', 'train'] %}
   -e {{ overcloud_templates_path }}/environments/disable-telemetry.yaml
   {% endif %}

ephemeral_heat: "{{ (release not in ['train','ussuri','victoria']) | bool }}"
ephemeral_heat_args: "{{ '--heat-type pod' if ephemeral_heat|bool else '' }}"

extra_args: >-
   {% if release not in ['newton', 'ocata', 'pike'] %}
   -e {{ overcloud_templates_path }}/ci/environments/ovb-ha.yaml
   {% endif %}
   {% if release not in ['newton','ocata','pike','queens','stein','train', 'ussuri'] -%}
   --disable-validations
   {% endif %}
   {% if release not in ['train','ussuri','victoria'] -%}
   --disable-protected-resource-types
   {%- endif -%}

# keep the doc gen settings at the bottom of the config file.
# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - "{% if release not in ['newton', 'ocata', 'pike'] -%}overcloud-prep-containers{%- endif -%}"
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
    - tempest-setup
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - "{% if release not in ['newton', 'ocata', 'pike'] -%}overcloud-prep-containers{%- endif -%}"
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
    - tempest-setup

deploy_steps_ansible_workflow: >-
  {% if release not in ['newton','ocata','pike'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
config_download_args: >-
  {% if release in ['queens'] -%}
  -e /usr/share/openstack-tripleo-heat-templates/environments/config-download-environment.yaml
  --config-download
  --verbose
  {%- endif -%}

# Tempest configuration, keep always at the end of the file
# Use the traditional ping test in newton, ocata and pike
# Run tempest in queens+

test_ping: >-
  {% if release in ['newton', 'ocata', 'pike'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

# Settings for os_tempest
use_os_tempest: >-
  {% if release not in ['pike', 'queens', 'stein'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

# It will create a public network name 'public' using os_tempest
tempest_interface_name: public

# In order to have a public network with external connectivity, we need to use
# flat network type
tempest_public_net_provider_type: flat

# It is the physical network name through which public network will be created
# having connectivity with external world.
tempest_public_net_physical_name: datacentre

# Setting the tempest_cidr as it is required while creating public subnet from which
# floating IPs gets assigned
tempest_cidr: '192.168.24.0/24'

tempest_private_net_seg_id: ''

tempest_install_method: distro

# Having tempest_network_ping_gateway set to true allows to ping any of the IP from
# router to find out network related issue in the deployment early
tempest_network_ping_gateway: true

# It is the python-tempestconf profile which also consumes tempest-deployer-input file
tempest_tempestconf_profile:
  debug: true
  create: true
  deployer-input: "{{ ansible_user_dir }}/tempest-deployer-input.conf"
  os-cloud: "{{ tempest_cloud_name }}"
  out: "{{ tempest_workspace }}/etc/tempest.conf"
  network-id: "{{ tempest_neutron_public_network_id }}"
  overrides: "{{ tempest_tempest_conf_overrides | default({}) }}"

# looking for a small set of tempest tests to validate
# tempest config and execution are working
test_white_regex: 'tempest.api.compute.admin'

tempest_test_whitelist:
  - 'tempest.api.compute.admin'
