---
- name: Create repo setup script
  template:
    src: "{{ repo_setup_script_source }}"
    dest: "{{ repo_setup_dir }}/{{ repo_setup_script }}"
    mode: 0755
  when: not use_yum_config_module|default(false)|bool

# When using tripleo-repos yum-config, split into 3 phases
- block:
    - name: Create script - commands before repo setup
      template:
        src: "{{ repo_cmd_before_setup_template }}"
        dest: "{{ repo_setup_dir }}/{{ repo_cmd_before_setup_script }}"
        mode: 0755
    - name: Create repo setup script (new)
      template:
        src: "{{ repo_setup_new_template }}"
        dest: "{{ repo_setup_dir }}/{{ repo_setup_new_script }}"
        mode: 0755
    - name: Create script - commands after repo setup
      template:
        src: "{{ repo_cmd_after_setup_template }}"
        dest: "{{ repo_setup_dir }}/{{ repo_cmd_after_setup_script }}"
        mode: 0755
  when: use_yum_config_module|default(false)|bool
