---
- name: Check DLRN hash format
  fail:
    msg: "The DLRN hash or tag is not recognized. The hash or tag should not contain path slashes."
  when:
    - not dlrn_hash_tag is match(expected_commit_distro_hash_regex)
    - not dlrn_hash_tag is match(expected_aggregate_hash_regex)
    - dlrn_hash_tag not in known_hash_tags

- name: Check DLRN hash - passed ready hash
  set_fact:
    dlrn_hash: "{{ dlrn_hash_tag }}"
    cacheable: true
  when: dlrn_hash_tag is match(expected_commit_distro_hash_regex) or dlrn_hash_tag is match(expected_aggregate_hash_regex)

# explicitly set python3 in centos7 https://bugs.launchpad.net/tripleo/+bug/1943968
- include_tasks: tripleo-get-hash-set-fact.yml
  vars:
    search_tag: "{{ dlrn_hash_tag }}"
    fact_name: "dlrn_hash"
    ansible_python_interpreter: /usr/bin/python3
  when:
    - dlrn_hash_tag in known_hash_tags
    - ansible_distribution_major_version is version(8, '<')

# dont set interpreter for centos8 https://bugs.launchpad.net/tripleo/+bug/1945127
- include_tasks: tripleo-get-hash-set-fact.yml
  vars:
    search_tag: "{{ dlrn_hash_tag }}"
    fact_name: "dlrn_hash"
  when:
    - dlrn_hash_tag in known_hash_tags
    - ansible_distribution_major_version is version(8, '>=')
    - repo_setup_use_collections

- include_tasks: tripleo-get-hash-set-fact-no-collections.yml
  vars:
    search_tag: "{{ dlrn_hash_tag }}"
    fact_name: "dlrn_hash"
  when:
    - dlrn_hash_tag in known_hash_tags
    - ansible_distribution_major_version is version(8, '>=')
    - not repo_setup_use_collections

# TODO: Fix for fedora
- when: overcloud_release is defined and (overcloud_release | length != 0)
  block:

    - name: Get DLRN overcloud hash
      shell: |
        set -euo pipefail
        dlrn_base=https://trunk.rdoproject.org/centos7-{{ overcloud_release }}
        if [ -e /etc/ci/mirror_info.sh ]; then
          source /etc/ci/mirror_info.sh
          NODEPOOL_RDO_PROXY=${NODEPOOL_RDO_PROXY:-https://trunk.rdoproject.org}
          dlrn_base=${dlrn_base/https:\/\/trunk.rdoproject.org/$NODEPOOL_RDO_PROXY}
        fi
        curl -s --fail --show-error ${dlrn_base}/{{ dlrn_hash_tag }}/delorean.repo \
        | grep baseurl | grep -Eo {{ expected_commit_distro_hash_regex }}
      register: full_overcloud_hash_result
      retries: 5

    - name: Set fact for overcloud dlrn_hash
      set_fact:
        overcloud_dlrn_hash: "{{ full_overcloud_hash_result.stdout }}"
        cacheable: true

    - name: Set fact for overcloud dlrn_hash path
      set_fact:
        overcloud_dlrn_hash_path: "{{ overcloud_dlrn_hash[:2] }}/{{ overcloud_dlrn_hash[2:4] }}/{{ overcloud_dlrn_hash }}"
        cacheable: true

    - name: Set fact for the overcloud Docker image tag
      set_fact:
        overcloud_docker_image_tag: "{{ overcloud_dlrn_hash }}"
        cacheable: true

- name: Set fact for dlrn_hash path
  set_fact:
    dlrn_hash_path: "{{ dlrn_hash[:2] }}/{{ dlrn_hash[2:4] }}/{{ dlrn_hash }}"
    cacheable: true

- name: Set fact for the Docker image tag
  set_fact:
    docker_image_tag: "{{ dlrn_hash }}"
    cacheable: true

- name: Set fact for task already run
  set_fact:
    dlrn_task_run: true
    cacheable: true
