---
- name: Check DLRN hash newest format
  fail:
    msg: "The newest DLRN hash or tag is not recognized. The hash or tag should not contain path slashes."
  when:
    - not dlrn_hash_tag_newest is match(expected_commit_distro_hash_regex)
    - not dlrn_hash_tag_newest is match(expected_aggregate_hash_regex)
    - dlrn_hash_tag_newest not in known_hash_tags

- name: Check DLRN hash newest - passed ready hash
  set_fact:
    dlrn_hash_newest: "{{ dlrn_hash_tag_newest }}"
    cacheable: true
  when: dlrn_hash_tag_newest is match(expected_commit_distro_hash_regex) or dlrn_hash_tag_newest is match(expected_aggregate_hash_regex)

# explicitly set python3 in centos7 https://bugs.launchpad.net/tripleo/+bug/1943968
- include_tasks: tripleo-get-hash-set-fact.yml
  vars:
    search_tag: "{{ dlrn_hash_tag_newest }}"
    fact_name: "dlrn_hash_newest"
    ansible_python_interpreter: /usr/bin/python3
  when:
    - dlrn_hash_tag in known_hash_tags
    - ansible_distribution_major_version is version(8, '<')

# dont set interpreter for centos8 https://bugs.launchpad.net/tripleo/+bug/1945127
- include_tasks: tripleo-get-hash-set-fact.yml
  vars:
    search_tag: "{{ dlrn_hash_tag_newest }}"
    fact_name: "dlrn_hash_newest"
  when:
    - dlrn_hash_tag_newest in known_hash_tags
    - ansible_distribution_major_version is version(8, '>=')
    - repo_setup_use_collections

- include_tasks: tripleo-get-hash-set-fact-no-collections.yml
  vars:
    search_tag: "{{ dlrn_hash_tag_newest }}"
    fact_name: "dlrn_hash_newest"
  when:
    - dlrn_hash_tag_newest in known_hash_tags
    - ansible_distribution_major_version is version(8, '>=')
    - not repo_setup_use_collections

- name: Set fact for dlrn_hash_path_newest
  set_fact:
    dlrn_hash_path_newest: "{{ dlrn_hash_newest[:2] }}/{{ dlrn_hash_newest[2:4] }}/{{ dlrn_hash_newest }}"
    cacheable: true

- name: Set fact for task already run
  set_fact:
    dlrn_task_run_newest: true
    cacheable: true
