---
- name: Check DLRN hash newest format
  fail:
    msg: "The newest DLRN hash or tag is not recognized. The hash or tag should not contain path slashes."
  when:
    - not dlrn_hash_tag_newest is match(expected_commit_distro_hash_regex)
    - not dlrn_hash_tag_newest is match(expected_aggregate_hash_regex)
    - dlrn_hash_tag_newest not in known_hash_tags

- name: print out the release name
  debug:
    msg: "the tq release is: {{ release }}"

- name: Check DLRN hash newest - passed ready hash
  set_fact:
    dlrn_hash_newest: "{{ dlrn_hash_tag_newest }}"
    cacheable: true
  when: dlrn_hash_tag_newest is match(expected_commit_distro_hash_regex) or dlrn_hash_tag is match(expected_aggregate_hash_regex)

- when:
    - dlrn_hash_tag_newest in known_hash_tags
    - ansible_distribution_major_version is version(8, '<')

  block:

    - name: Get DLRN hash newest - passed tag
      shell: |
        set -euo pipefail
        dlrn_base={{ dlrn_baseurl }}
        if [ -e /etc/ci/mirror_info.sh ]; then
          source /etc/ci/mirror_info.sh
          NODEPOOL_RDO_PROXY=${NODEPOOL_RDO_PROXY:-https://trunk.rdoproject.org}
          dlrn_base=${dlrn_base/https:\/\/trunk.rdoproject.org/$NODEPOOL_RDO_PROXY}
        fi
        curl -s --fail --show-error ${dlrn_base}/{{ dlrn_hash_tag_newest }}/delorean.repo \
        | grep baseurl | grep -Eo {{ expected_commit_distro_hash_regex | quote }}
      register: full_hash_newest_result
      retries: 5

    - name: Set fact for dlrn_hash_newest
      set_fact:
        dlrn_hash_newest: "{{ full_hash_newest_result.stdout }}"
        cacheable: true

# when running a component job, the containers and images
# come from a promoted current-tripleo pin.  Therefore the md5
# of the known hash_tag (e..g. current tripleo) is the cricital hash to know.
# components for OSP will be built on OSP-16, 17 # TO-DO
- when:
    - dlrn_hash_tag_newest in known_hash_tags
    - ansible_distribution_major_version is version(8, '>=')
  block:
    - name: Get DLRN hash newest - passed tag - component-based
      shell: |
        set -euo pipefail
        dlrn_base={{ dlrn_baseurl }}
        if [ -e /etc/ci/mirror_info.sh ]; then
          source /etc/ci/mirror_info.sh
          NODEPOOL_RDO_PROXY=${NODEPOOL_RDO_PROXY:-https://trunk.rdoproject.org}
          dlrn_base=${dlrn_base/https:\/\/trunk.rdoproject.org/$NODEPOOL_RDO_PROXY}
        fi
        curl -s --fail --show-error ${dlrn_base}/{{ dlrn_hash_tag_newest }}/delorean.repo.md5
      register: full_hash_result
      retries: 5

    - name: Set fact for dlrn_hash_newest
      set_fact:
        dlrn_hash_newest: "{{ full_hash_result.stdout }}"
        cacheable: true

- name: Set fact for dlrn_hash_path_newest
  set_fact:
    dlrn_hash_path_newest: "{{ dlrn_hash_newest[:2] }}/{{ dlrn_hash_newest[2:4] }}/{{ dlrn_hash_newest }}"
    cacheable: true

- name: Set fact for task already run
  set_fact:
    dlrn_task_run_newest: true
    cacheable: true
