---
- name: 'resolve {{ search_tag }} with tripleo-get-hash python cli via shell'
  block:
    - name: 'Set facts for tripleo-get-hash parameters'
      set_fact:
        tgh_release: "{{ dir_release | default(release) }}"
        tgh_os_version: "{{ distro_ver }}"
        tgh_dlrn_url: "{{ dlrn_baseurl|urlsplit('scheme') }}://{{ dlrn_baseurl|urlsplit('hostname') }}"
    - name: 'tripleo-get-hash {{ search_tag }} for {{ tgh_release }} on {{ tgh_os_version }} from {{ tgh_dlrn_url }}'
      shell: |
        tripleo-get-hash --release {{ tgh_release }} --os-version {{ tgh_os_version }} --tag {{ search_tag }} --dlrn-url {{ tgh_dlrn_url }}
      register: tripleo_get_hash_result
      until: tripleo_get_hash_result is success
      retries: 5
  rescue:
    - include_tasks: set_fact_nodepool_rdo_proxy.yml
    - name: 'tripleo-get-hash {{ search_tag }} for {{ tgh_release }} on {{ tgh_os_version }} from {{ nodepool_rdo_proxy }}'
      shell: |
        tripleo-get-hash --release {{ tgh_release }} --os-version {{ tgh_os_version }} --tag {{ search_tag }} --dlrn-url {{ nodepool_rdo_proxy }}
      register: tripleo_get_hash_result
      until: tripleo_get_hash_result is success
      retries: 5

- name: find full hash line from tripleo-get-hash stdout_lines
  set_fact:
    full_hash_line: "{{ item }}"
  when: "'full_hash' in item"
  with_items: "{{ tripleo_get_hash_result.stdout_lines }}"

- name: "Set fact {{ fact_name }}->{{ full_hash_line.split(':')[1][1:-1] }}"
  set_fact:
    "{{ fact_name }}": "{{ full_hash_line.split(':')[1][1:-1] }}"
    cacheable: true
