# global build vars
working_dir: /var/lib/oooq-images

# publish vars
artifacts:
  - undercloud.qcow2
  - undercloud.qcow2.md5
  - ironic-python-agent.tar
  - ironic-python-agent.tar.md5
  - overcloud-full.tar
  - overcloud-full.tar.md5
release: mitaka
build_system: delorean

publish: false
publish_dest_user:           rdo
publish_dest_host:           artifacts.ci.centos.org
publish_dest_basepath:       rdo/images
publish_create_dest_via_ssh: false

# optional
# publish_dest_key: "localpath/to/your/identity/file"

artib_image_stage_location: testing
