release: master
undercloud_image_url: http://artifacts.ci.centos.org/artifacts/rdo/images/master/delorean/consistent/testing/undercloud.qcow2
overcloud_image_url: http://artifacts.ci.centos.org/artifacts/rdo/images/master/delorean/consistent/testing/overcloud-full.tar
ipa_image_url: http://artifacts.ci.centos.org/artifacts/rdo/images/master/delorean/consistent/testing/ironic-python-agent.tar

