# Error out early if the `virthost` variable is not set.
- name: Check that virthost is set
  fail:
    msg: "You need to set virthost before running these playbooks."
  when: virthost is not defined

- name: Get current user group for localhost
  command: "id -gn"
  register: local_user_group
  changed_when: false

- name: Register fact for current user group
  set_fact: current_group_local="{{ local_user_group.stdout }}"
  tags:
    - provision

- name: Ensure local working dir exists
  file:
    path: "{{ local_working_dir }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ current_group_local }}"
  become: true

# This file needs to exist because it will later be referenced in some
# ssh command lines.
- name: Create empty ssh config file
  file:
    path: "{{ local_working_dir }}/ssh.config.ansible"
    state: touch

# Add the virthost to the in-memory inventory.  The inventory is not
# written out to disk unless you call the `tripleo-inventory` role.
- name: Add the virthost to the inventory
  add_host:
    name: "{{virthost}}"
    groups: "virthost"
    ansible_fqdn: "{{ virthost }}"
    ansible_user: "root"
    ansible_host: "{{ virthost }}"
