devmode: true
overcloud_as_undercloud: true
images:
    - name: overcloud-full
      url: "{{ overcloud_image_url }}"
      type: tar
    - name: ipa_images
      url: "{{ ipa_image_url }}"
      type: tar
inject_images:
    - "ironic-python-agent.initramfs"
    - "ironic-python-agent.vmlinuz"
    - "ironic-python-agent.kernel"
    - "overcloud-full.qcow2"
    - "overcloud-full.initrd"
    - "overcloud-full.vmlinuz"
release: master
overcloud_image_url: http://66.187.229.139/builds/current-tripleo/overcloud-full.tar
ipa_image_url: http://66.187.229.139/builds/current-tripleo/ipa_images.tar
repos:
  - type: generic
    reponame: delorean
    filename: delorean.repo
    baseurl: http://trunk.rdoproject.org/centos7/consistent
    hash_url: http://trunk.rdoproject.org/centos7/consistent/delorean.repo
    priority: 20

  - type: file
    filename: delorean-deps.repo
    down_url: http://trunk.rdoproject.org/centos7-master/delorean-deps.repo

  - type: package
    pkg_name: centos-release-ceph-jewel
    custom_cmd: 'sudo yum install -y --enablerepo=extras'

  - type: generic
    reponame: centos-opstools
    filename: centos-opstools.repo
    baseurl: https://buildlogs.centos.org/centos/7/opstools/x86_64/

repo_cmd_after: |
  {% if not enable_opstools_repo|default(false)|bool %}sudo yum-config-manager --save --setopt centos-opstools.enable=0;
  {%endif %}
  sudo rpm -e epel-release || true;
  sudo yum remove -y rdo-release || true;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  sudo yum-config-manager --save --setopt centos-ceph-jewel.gpgcheck=0;
  sudo yum repolist;
  sudo yum update -y
