release: pike
overcloud_release: ocata
undercloud_image_url: https://images.rdoproject.org/pike/delorean/current-tripleo/stable/undercloud.qcow2
ipa_image_url: http://66.187.229.139/builds-pike/current-tripleo-pike/ipa_images.tar
overcloud_image_url: http://66.187.229.139/builds-ocata/current-tripleo-ocata/overcloud-full.tar
images:
    - name: undercloud
      url: "{{ undercloud_image_url }}"
      type: qcow2
    - name: overcloud-full
      url: "{{ overcloud_image_url }}"
      type: tar
    - name: ipa_images
      url: "{{ ipa_image_url }}"
      type: tar

use_external_images: true
inject_images:
    - "ironic-python-agent.initramfs"
    - "ironic-python-agent.vmlinuz"
    - "ironic-python-agent.kernel"
    - "overcloud-full.qcow2"
    - "overcloud-full.initrd"
    - "overcloud-full.vmlinuz"

repo_cmd_before: |
  sudo rm -rf /etc/yum.repos.d/delorean*;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  sudo yum clean all;
  sudo yum-config-manager --disable "*"
  export CURRENT_RDO_MIRROR=`curl -L --silent https://trunk.rdoproject.org/centos7-pike/consistent/delorean.repo | grep baseurl | cut -d= -f2`
  export CURRENT_TRIPLEO_MIRROR=`curl -L --silent https://trunk.rdoproject.org/centos7-pike/current-tripleo/delorean.repo | grep baseurl | cut -d= -f2`
  # If running tripleo-quickstart from review.openstack.org or review.rdoproject.org, try to use AFS mirrors
  if [[ -e /etc/ci/mirror_info.sh ]]; then
  eval $(source /etc/ci/mirror_info.sh; echo NODEPOOL_MIRROR_HOST="$NODEPOOL_MIRROR_HOST"; echo NODEPOOL_BUILDLOGS_CENTOS_PROXY="$NODEPOOL_BUILDLOGS_CENTOS_PROXY")
  export NODEPOOL_MIRROR_HOST="http://${NODEPOOL_MIRROR_HOST}"
  export NODEPOOL_BUILDLOGS_CENTOS_PROXY=$NODEPOOL_BUILDLOGS_CENTOS_PROXY
  export CURRENT_RDO_MIRROR=${CURRENT_RDO_MIRROR/https:\/\/trunk.rdoproject.org/$NODEPOOL_MIRROR_HOST:8080/rdo}
  export CURRENT_TRIPLEO_MIRROR=${CURRENT_TRIPLEO_MIRROR/https:\/\/trunk.rdoproject.org/$NODEPOOL_MIRROR_HOST:8080/rdo}
  fi
  # Otherwise, fallback to official mirrors provided by CentOS.
  export NODEPOOL_MIRROR_HOST="${NODEPOOL_MIRROR_HOST:-http://mirror.centos.org}"
  export NODEPOOL_BUILDLOGS_CENTOS_PROXY="${NODEPOOL_BUILDLOGS_CENTOS_PROXY:-https://buildlogs.centos.org}"
repos:
  # RDO repos
  - type: generic
    reponame: delorean
    filename: delorean.repo
    baseurl: $CURRENT_TRIPLEO_MIRROR
    priority: 20
    hash_url: https://trunk.rdoproject.org/centos7-pike/current-tripleo/delorean.repo

  - type: generic
    reponame: delorean-pike-testing
    filename: delorean-pike-testing.repo
    baseurl: ${NODEPOOL_BUILDLOGS_CENTOS_PROXY}/centos/7/cloud/x86_64/openstack-pike/

  # CentOS related repos
  - type: generic
    reponame: quickstart-centos-base
    filename: quickstart-centos-base.repo
    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/os/x86_64/

  - type: generic
    reponame: quickstart-centos-updates
    filename: quickstart-centos-updates.repo
    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/updates/x86_64/

  - type: generic
    reponame: quickstart-centos-extras
    filename: quickstart-centos-extras.repo
    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/extras/x86_64/

  - type: generic
    reponame: quickstart-centos-qemu
    filename: quickstart-centos-qemu.repo
    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/virt/x86_64/kvm-common/

  - type: generic
    reponame: quickstart-centos-ceph-jewel
    filename: quickstart-centos-ceph-jewel.repo
    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/storage/x86_64/ceph-jewel/

  - type: generic
    reponame: quickstart-centos-opstools
    filename: quickstart-centos-opstools.repo
    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/opstools/x86_64/

repo_cmd_after: |
  sudo yum install -y yum-plugin-priorities;
  {% if not enable_opstools_repo|default(false)|bool %}sudo yum-config-manager --save --setopt centos-opstools.enable=0;
  {%endif %}
  sudo yum-config-manager --disable rdo-qemu-ev;
  sudo rpm -e epel-release || true;
  sudo yum remove -y rdo-release || true;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  sudo yum repolist;
  sudo yum update -y
