release: queens
overcloud_release: newton
target_upgrade_version: queens

overcloud_templates_branch: newton-eol
overcloud_templates_repo: https://git.openstack.org/openstack/tripleo-heat-templates
overcloud_templates_path: "{{working_dir}}/tripleo-heat-templates"

dlrn_hash_tag: current-passed-ci
dlrn_hash_tag_newest: current

undercloud_image_url: https://images.rdoproject.org/queens/delorean/{{ dlrn_hash|default(dlrn_hash_tag) }}/undercloud.qcow2
ipa_image_url: https://images.rdoproject.org/queens/delorean/{{ dlrn_hash|default(dlrn_hash_tag) }}/ironic-python-agent.tar

# This doesnâ€™t follow the usual pattern, but
# netwon/delorean/consistent/stable seems to be more up to date.
overcloud_image_url: https://images.rdoproject.org/newton/delorean/consistent/stable/overcloud-full.tar
use_external_images: true

images:
    - name: undercloud
      url: "{{ undercloud_image_url }}"
      type: qcow2
    - name: overcloud-full
      url: "{{ overcloud_image_url }}"
      type: tar
    - name: ipa_images
      url: "{{ ipa_image_url }}"
      type: tar

inject_images:
    - "ironic-python-agent.initramfs"
    - "ironic-python-agent.kernel"
    - "overcloud-full.qcow2"
    - "overcloud-full.initrd"
    - "overcloud-full.vmlinuz"

repo_cmd_before: |
  sudo rm -rf /etc/yum.repos.d/delorean*;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  sudo yum clean all;
  sudo yum-config-manager --disable "*"
  if [ -e /etc/ci/mirror_info.sh ]; then
    source /etc/ci/mirror_info.sh
  else
    # Otherwise, fallback to official mirrors provided by CentOS.
    export NODEPOOL_CENTOS_MIRROR=http://mirror.centos.org/centos
    export NODEPOOL_BUILDLOGS_CENTOS_PROXY=https://buildlogs.centos.org
    export NODEPOOL_RDO_PROXY=https://trunk.rdoproject.org
  fi
  rdo_dlrn=`curl --silent ${NODEPOOL_RDO_PROXY}/centos7-queens/{{ dlrn_hash_path_newest|default(dlrn_hash_tag_newest) }}/delorean.repo -S 2>>~/dlrn_repo_curl_errors.log | grep baseurl | cut -d= -f2`
  tripleo_dlrn=`curl --silent ${NODEPOOL_RDO_PROXY}/centos7-queens/{{ dlrn_hash_path|default(dlrn_hash_tag) }}/delorean.repo -S 2>>~/dlrn_repo_curl_errors.log | grep baseurl | cut -d= -f2`
  if [[ -z "$rdo_dlrn" || -z "$tripleo_dlrn" ]]; then
    echo "Failed to parse dlrn hash"
    exit 1
  fi
  export RDO_DLRN_REPO=${rdo_dlrn/https:\/\/trunk.rdoproject.org/$NODEPOOL_RDO_PROXY}
  export TRIPLEO_DLRN_REPO=${tripleo_dlrn/https:\/\/trunk.rdoproject.org/$NODEPOOL_RDO_PROXY}

repos:
  # RDO repos
  - type: generic
    reponame: delorean
    filename: delorean.repo
    priority: 20
    baseurl: $TRIPLEO_DLRN_REPO

  - type: generic
    reponame: delorean-current
    filename: delorean-current.repo
    baseurl: $RDO_DLRN_REPO
    priority: 10
    includepkgs:
      - instack
      - instack-undercloud
      - os-apply-config
      - os-collect-config
      - os-net-config
      - os-refresh-config
      - python-tripleoclient
      - openstack-tripleo-*
      - puppet-*
      - python-paunch

  - type: generic
    reponame: delorean-queens-deps
    filename: delorean-queens-deps.repo
    baseurl: ${NODEPOOL_RDO_PROXY}/centos7-queens/deps/latest/

  # CentOS related repos
  - type: generic
    reponame: quickstart-centos-base
    filename: quickstart-centos-base.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/7/os/x86_64/

  - type: generic
    reponame: quickstart-centos-updates
    filename: quickstart-centos-updates.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/7/updates/x86_64/

  - type: generic
    reponame: quickstart-centos-extras
    filename: quickstart-centos-extras.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/7/extras/x86_64/

  - type: generic
    reponame: quickstart-centos-qemu
    filename: quickstart-centos-qemu.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/7/virt/x86_64/kvm-common/

  - type: generic
    reponame: quickstart-centos-ceph-luminous
    filename: quickstart-centos-ceph-luminous.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/7/storage/x86_64/ceph-luminous/

  - type: generic
    reponame: quickstart-centos-opstools
    filename: quickstart-centos-opstools.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/7/opstools/x86_64/

repo_cmd_after: |
  sudo yum install -y yum-plugin-priorities;
  {% if not enable_opstools_repo|default(false)|bool %}sudo yum-config-manager --save --setopt quickstart-centos-opstools.enabled=0;
  {%endif %}
  sudo yum-config-manager --disable rdo-qemu-ev;
  sudo rpm -e epel-release || true;
  sudo yum remove -y rdo-release centos-release-ceph-* centos-release-openstack-* centos-release-qemu-ev || true;
  sudo rm -rf /etc/yum.repos.d/CentOS-OpenStack-*.repo /etc/yum.repos.d/CentOS-Ceph-*.repo /etc/yum.repos.d/CentOS-QEMU-EV.repo;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  sudo yum repolist;
  sudo yum clean metadata
  {% if repo_setup_run_update|default(true)|bool %}
   sudo yum update -y
  {% endif %}

undercloud_rpm_dependencies: >-
  python-tripleoclient
  ceph-ansible
