release: queens
#TODO Figure out if we can remove target_upgrade_version to replace by
#     release so we avoid duplication.
target_upgrade_version: queens
overcloud_release: pike
dlrn_hash_tag: current-tripleo
dlrn_hash_tag_newest: current
docker_registry_host: docker.io
docker_registry_namespace: "tripleo{{release}}"
docker_image_tag: "{{ dlrn_hash|default(dlrn_hash_tag) }}"
overcloud_docker_registry_namespace: "tripleo{{ overcloud_release }}"
overcloud_docker_image_tag: "{{ overcloud_dlrn_hash }}"

overcloud_templates_path: "{{ working_dir }}/tripleo-heat-templates"
overcloud_templates_repo: https://git.openstack.org/openstack/tripleo-heat-templates
overcloud_templates_branch: stable/{{ overcloud_release }}

undercloud_image_url: https://images.rdoproject.org/queens/delorean/{{ dlrn_hash|default(dlrn_hash_tag) }}/undercloud.qcow2
ipa_image_url: https://images.rdoproject.org/queens/delorean/{{ dlrn_hash|default(dlrn_hash_tag) }}/ironic-python-agent.tar
overcloud_image_url: https://images.rdoproject.org/pike/delorean/{{ overcloud_dlrn_hash|default(dlrn_hash_tag) }}/overcloud-full.tar
images:
    - name: undercloud
      url: "{{ undercloud_image_url }}"
      type: qcow2
    - name: overcloud-full
      url: "{{ overcloud_image_url }}"
      type: tar
    - name: ipa_images
      url: "{{ ipa_image_url }}"
      type: tar

use_external_images: true
inject_images:
    - "ironic-python-agent.initramfs"
    - "ironic-python-agent.kernel"
    - "overcloud-full.qcow2"
    - "overcloud-full.initrd"
    - "overcloud-full.vmlinuz"

repo_cmd_before: |
  sudo rm -rf /etc/yum.repos.d/delorean*;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  sudo yum clean all;
  sudo yum-config-manager --disable "*"
  export CURRENT_RDO_MIRROR=`curl -L --silent https://trunk.rdoproject.org/centos7-queens/{{ dlrn_hash_path_newest|default(dlrn_hash_tag_newest) }}/delorean.repo | grep baseurl | cut -d= -f2`
  export CURRENT_TRIPLEO_MIRROR=`curl -L --silent https://trunk.rdoproject.org/centos7-queens/{{ dlrn_hash_path|default(dlrn_hash_tag) }}/delorean.repo | grep baseurl | cut -d= -f2`
  # If running tripleo-quickstart from review.openstack.org or review.rdoproject.org, try to use AFS mirrors
  if [[ -e /etc/ci/mirror_info.sh ]]; then
  eval $(source /etc/ci/mirror_info.sh; echo NODEPOOL_MIRROR_HOST="$NODEPOOL_MIRROR_HOST"; echo NODEPOOL_BUILDLOGS_CENTOS_PROXY="$NODEPOOL_BUILDLOGS_CENTOS_PROXY")
  export NODEPOOL_MIRROR_HOST="http://${NODEPOOL_MIRROR_HOST}"
  export NODEPOOL_BUILDLOGS_CENTOS_PROXY=$NODEPOOL_BUILDLOGS_CENTOS_PROXY
  export CURRENT_RDO_MIRROR=${CURRENT_RDO_MIRROR/https:\/\/trunk.rdoproject.org/$NODEPOOL_MIRROR_HOST:8080/rdo}
  export CURRENT_TRIPLEO_MIRROR=${CURRENT_TRIPLEO_MIRROR/https:\/\/trunk.rdoproject.org/$NODEPOOL_MIRROR_HOST:8080/rdo}
  fi
  # Otherwise, fallback to official mirrors provided by CentOS.
  export NODEPOOL_MIRROR_HOST="${NODEPOOL_MIRROR_HOST:-http://mirror.centos.org}"
  export NODEPOOL_BUILDLOGS_CENTOS_PROXY="${NODEPOOL_BUILDLOGS_CENTOS_PROXY:-https://buildlogs.centos.org}"
  export NODEPOOL_RDO_PROXY="${NODEPOOL_RDO_PROXY:-https://trunk.rdoproject.org}"
repos:
  # RDO repos
  - type: generic
    reponame: delorean
    filename: delorean.repo
    baseurl: $CURRENT_TRIPLEO_MIRROR
    priority: 20
    hash_url: https://trunk.rdoproject.org/centos7-queens/{{ dlrn_hash_path|default(dlrn_hash_tag) }}/delorean.repo

  - type: generic
    reponame: delorean-current
    filename: delorean-current.repo
    baseurl: $CURRENT_RDO_MIRROR
    priority: 10
    includepkgs:
      - diskimage-builder
      - instack
      - instack-undercloud
      - os-apply-config
      - os-collect-config
      - os-net-config
      - os-refresh-config
      - python-tripleoclient*
      - openstack-tripleo-common*
      - openstack-tripleo-heat-templates
      - openstack-tripleo-image-elements
      - openstack-tripleo
      - openstack-tripleo-puppet-elements
      - openstack-puppet-modules
      - openstack-tripleo-ui
      - puppet-*

  - type: generic
    reponame: delorean-queens-deps
    filename: delorean-queens-deps.repo
    baseurl: ${NODEPOOL_RDO_PROXY}/centos7-queens/deps/latest/

  # CentOS related repos
  - type: generic
    reponame: quickstart-centos-base
    filename: quickstart-centos-base.repo
    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/os/x86_64/

  - type: generic
    reponame: quickstart-centos-updates
    filename: quickstart-centos-updates.repo
    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/updates/x86_64/

  - type: generic
    reponame: quickstart-centos-extras
    filename: quickstart-centos-extras.repo
    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/extras/x86_64/

  - type: generic
    reponame: quickstart-centos-qemu
    filename: quickstart-centos-qemu.repo
    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/virt/x86_64/kvm-common/

  - type: generic
    reponame: quickstart-centos-ceph-luminous
    filename: quickstart-centos-ceph-luminous.repo
    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/storage/x86_64/ceph-luminous/

  - type: generic
    reponame: quickstart-centos-opstools
    filename: quickstart-centos-opstools.repo
    baseurl: ${NODEPOOL_MIRROR_HOST}/centos/7/opstools/x86_64/

repo_cmd_after: |
  sudo yum install -y yum-plugin-priorities;
  {% if not enable_opstools_repo|default(false)|bool %}sudo yum-config-manager --save --setopt centos-opstools.enable=0;
  {%endif %}
  sudo yum-config-manager --disable rdo-qemu-ev;
  sudo rpm -e epel-release || true;
  sudo yum remove -y rdo-release || true;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  sudo yum repolist;
  sudo yum clean metadata
  {% if repo_setup_run_update|default(true)|bool %}
  sudo yum update -y
  {% endif %}

undercloud_rpm_dependencies: >-
  python-tripleoclient
  ceph-ansible
