working_dir: "{{ ansible_user_dir }}/.quickstart"
image_cache_dir: "{{ ansible_user_dir }}/oooq_cache"
release: mitaka
image_url: http://artifacts.ci.centos.org/rdo/images/{{ release }}/delorean/stable/undercloud.qcow2
nova_power_manager: 'nova.virt.baremetal.virtual_power_driver.VirtualPowerManager'

virt_power_key: "{{ local_working_dir }}/id_rsa_virt_power"
undercloud_key: "{{ local_working_dir }}/id_rsa_undercloud"

libvirt_uri: qemu:///session
libvirt_volume_path: "{{ working_dir }}/pool"
libvirt_volume_pool: oooq_pool
libvirt_domain_type: kvm
libvirt_diskbus: sata
libvirt_arch: x86_64
