libvirt_packages:
  - libvirt
  - libvirt-daemon
  - qemu-kvm-common
  - qemu-kvm
  - libvirt-daemon-kvm
  - libvirt-daemon-driver-network
  - libvirt-daemon-driver-qemu
  - libguestfs-tools
  - python3
  - python3-lxml
  - python3-netaddr
  - python3-pip
  - python3-devel
  - python3-libvirt

ansible_pkg_mgr: dnf
