---
repo_setup_dir: "{{ working_dir }}"
repo_setup_script: repo_setup.sh.j2
repo_setup_log: "{{ repo_setup_dir }}/repo_setup.log"
repo_run_live: true
# Releases shortcuts
stable:
  - newton
  - mitaka
  - liberty
repo_cmd_before: |
  sudo yum install -y yum-plugin-priorities;
  sudo yum clean all;
  sudo rm -rf /etc/yum.repos.d/delorean*;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
repo_cmd_after: |
  sudo yum repolist;
  sudo yum update -y

# Repositories definitions
repos:
  - type: file
    filename: delorean.repo
    down_url: https://trunk.rdoproject.org/centos7-{{ release }}/current/delorean.repo

  - type: file
    filename: delorean-deps.repo
    down_url: https://trunk.rdoproject.org/centos7-{{ release }}/delorean-deps.repo

# For adding custom repositories in featureset files
add_repos: []
# rhsm variables
use_rhsm: false
use_use_rhsm_baseos_channel: true
use_rhsm_openstack_channel: true
use_rhsm_ceph_channel: true

rhsm_username: none
rhsm_password: none
pool_id: none
rhel_version_number: 7
osp_release_version_number: 8
rhceph_version_number: "1.3"
use_specific_hash: false
delorean_hash_label: latest
known_hash_tags:
  - current
  - consistent
  - tripleo-ci-testing
  - current-tripleo
  - current-tripleo-rdo
  - current-tripleo-rdo-internal
  - current-passed-ci
