---
repo_setup_dir: "{{ working_dir }}"
repo_setup_script_source: repo_setup.sh.j2
repo_setup_script: repo_setup.sh
repo_setup_log: repo_setup.log
# New repo_setup based on triple-repos
repo_cmd_before_setup_template: repo_cmd_before_setup.sh.j2
repo_cmd_after_setup_template: repo_cmd_after_setup.sh.j2
repo_cmd_before_setup_script: repo_cmd_before_setup.sh
repo_cmd_after_setup_script: repo_cmd_after_setup.sh
repo_setup_new_template: repo_setup_new.sh.j2
repo_setup_new_script: repo_setup_new.sh
# File to temporary store environment variables which will be loaded in repo_setup_newest.sh and repo_cmd_after_setup.sh
repo_setup_env_filepath: "/tmp/repo_setup_env"
repo_run_live: true
repo_setup_use_collections: true  # for zuul native cannot use this
# Releases shortcuts
stable:
  - pike
  - ocata
  - queens
  - stein
  - train
repo_cmd_before: |
  {% if ansible_pkg_mgr == "yum" %}
  sudo {{ ansible_pkg_mgr }} install -y yum-plugin-priorities;
  {% endif %}
  sudo {{ ansible_pkg_mgr }} clean all;
  sudo rm -rf /etc/yum.repos.d/delorean*;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
repo_cmd_after: |
  sudo {{ ansible_pkg_mgr }} repolist;
  sudo {{ ansible_pkg_mgr }} update -y

# Repositories definitions
dlrn_baseurl: "https://trunk.rdoproject.org/centos{{ ansible_distribution_major_version | default('7') }}-{{ release }}"
repos:
  - type: file
    filename: delorean.repo
    down_url: "{{ dlrn_baseurl }}/current/delorean.repo"

  - type: file
    filename: delorean-deps.repo
    down_url: "{{ dlrn_baseurl }}/delorean-deps.repo"

repo_setup_run_update: true

# For adding custom repositories in featureset files
add_repos: []
# rhsm variables
use_rhsm: false
use_use_rhsm_baseos_channel: true
use_rhsm_openstack_channel: true
use_rhsm_ceph_channel: true

rhsm_username: none
rhsm_password: none
pool_id: none
rhel_version_number: 7
osp_release_version_number: 8
rhceph_version_number: "1.3"
use_specific_hash: false
delorean_hash_label: latest
known_hash_tags:
  - current
  - consistent
  - tripleo-ci-testing
  - current-tripleo
  - current-tripleo-rdo
  - current-tripleo-rdo-internal
  - current-passed-ci
  - promoted-components
  - component-ci-testing
expected_commit_distro_hash_regex: "[a-zA-Z0-9]{40}_[a-zA-Z0-9]{8}$"
expected_aggregate_hash_regex: "^[a-zA-Z0-9]{32}$"
