# This config file is used to deploy a dedicated node in the overcloud for ceph

# Define a controller node, a compute node, and a ceph node.
overcloud_nodes:
  - name: control_0
    flavor: control
    virtualbmc_port: 6230

  - name: compute_0
    flavor: compute
    virtualbmc_port: 6231

  - name: ceph_0
    flavor: ceph
    virtualbmc_port: 6232

# Tell tripleo which nodes to deploy.
topology: >-
  --ceph-storage-scale 1
  -e {{overcloud_templates_path}}/environments/storage-environment.yaml

network_isolation: true
network_isolation_type: 'single-nic-vlans'
