---
- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: virthost
  gather_facts: yes
  roles:
    - libvirt/setup

- name: Add nodes to the generated inventory
  hosts: localhost
  gather_facts: yes
  roles:
    - tripleo-inventory

