---
- include: provision.yml

- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: virthost
  gather_facts: yes
  roles:
    - libvirt/teardown
    - libvirt/setup

- name: Rebuild inventory
  hosts: localhost
  gather_facts: no
  vars:
    # This allows running ansible in a virtualenv,
    # while using python from the base install
    ansible_python_interpreter: "/usr/bin/python"
  roles:
    - rebuild-inventory

- name:  Install undercloud and deploy overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo/undercloud
    - tripleo/overcloud
